### ISSUE TITLE
Messages from Discord are empty with discord.py>2

### ISSUE THREAD

**Issue by JulienPalard** [Hackndo/discord-irc-sync#13]
I upgraded my gate a few minutes ago, on #afpy on libera.chat. 

Messages from Discord are now empty see logs: https://logs.afpy.org/archives/2023/04/13

I'm having:

```
discord-irc-sync@deb2:~$ ./venv/bin/python -m pip list
Package            Version
------------------ -----------
aiohttp            3.7.4.post0
aiosignal          1.3.1
async-timeout      3.0.1
attrs              22.2.0
autocommand        2.2.2
chardet            4.0.0
charset-normalizer 3.1.0
discord            2.2.2
discord.py         2.2.2
frozenlist         1.3.3
idna               3.4
inflect            6.0.2
irc                20.1.0
jaraco.collections 4.0.0
jaraco.context     4.3.0
jaraco.functools   3.6.0
jaraco.logging     3.1.2
jaraco.stream      3.0.3
jaraco.text        3.11.1
more-itertools     9.1.0
multidict          6.0.4
pip                23.0.1
pydantic           1.10.7
pytz               2023.3
setuptools         67.6.1
tempora            5.2.1
typing_extensions  4.5.0
yarl               1.8.2
```

**Comment by JulienPalard** [comment]
` pip install --upgrade 'discord.py<2'` fixes it, still using 8f5c32ddd67869e196c0cf691f2afdbed769a0c3.

**Comment by Hackndo** [comment]
Enable `Message Content Intent` by navigating to your bot page (https://discord.com/developers/applications then choose your bot), under the bot menu, enable the `Message Content Intent` parameter so the bot can read messages and transfer them to IRC.

**Comment by Hackndo** [comment]
And update to last version of the tool. You're right, the discord.py v2+ needs a special intent to read messages. Added in last commit. Thanks for bringing this up.
